name: Setup

description: Setup PHP and Composer

inputs:
  php-version:
    description: PHP version(s) you wish to use
    required: true
  php-extensions:
    description: The PHP extensions you wish to install
    required: false
    default: dom, curl, libxml, mbstring, zip, pcntl, pdo, gd, redis, igbinary, msgpack, lzf, zstd, lz4, memcached, gmp, :php-psr, pdo_mysql
  coverage:
    description: Coverage driver to use
    required: false
    default: none

runs:
  using: "composite"
  steps:
    - name: Get PHP extensions cache hash
      id: get-cache-hash
      run: echo "hash=$(echo ${{ inputs.php-extensions }} | md5sum | awk '{print $1}')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Setup cache environment
      id: extcache
      uses: shivammathur/cache-extensions@v1
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.php-extensions }}
        key: php-extensions-${{ steps.get-cache-hash.outputs.hash }}

    - name: Cache PHP extensions
      uses: actions/cache@v4
      with:
        path: ${{ steps.extcache.outputs.dir }}
        key: ${{ steps.extcache.outputs.key }}
        restore-keys: ${{ steps.extcache.outputs.key }}

    - name: Setup PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.php-extensions }}
        tools: composer:v2
        coverage: ${{ inputs.coverage }}

    - name: Get composer cache directory
      id: composer-cache-dir
      run: echo "cache_dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache composer dependencies
      uses: actions/cache@v4.2.4
      with:
        key: composer-cache-${{ hashFiles('**/composer.lock') }}
        path: ${{ steps.composer-cache-dir.outputs.cache_dir }}
        restore-keys: composer-cache-
