name: Laravel Pint

on:
  push:
    branches:
      - master

permissions:
  issues: write
  pull-requests: write

jobs:
  laravel-pint:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup
        uses: ./.github/actions/setup
        with:
          php-version: '8.3'
          php-extensions: 'json, dom, curl, libxml, mbstring'

      - name: Install Laravel Pint
        run: composer global require laravel/pint

      - name: Run Laravel Pint
        run: pint

      - name: Push changes back to Repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "gh-noreply@gmail.com"
          git add .
          git commit -m "Apply Laravel Pint formatting" || exit 0
          git push
